version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/
    networks:
      - php_network

  php:
    image: php:fpm
    volumes:
      - ./src:/var/www/html/
    networks:
      - php_network

networks:
  php_network:
    driver: bridge