version: '3'

services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/rust
    volumes:
      - ./src/:/home/rust/src
      - ./Cargo.toml/:/home/rust/Cargo.toml